//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrTech.Amal.SQLModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestUsr
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> GreenPoints { get; set; }
        public string FileName { get; set; }
        public string QRCode { get; set; }
        public string DeviceID { get; set; }
        public string OSType { get; set; }
        public string SocialMediaKey { get; set; }
        public string SocialMediaName { get; set; }
        public string Status { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> SMSCodeRequired { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string City { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<int> Redeemed { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string UnionCouncil { get; set; }
        public string Type { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> RefUserID { get; set; }
        public Nullable<decimal> WalletBalance { get; set; }
    }
}
